site_name: μGPD Analysis Tool
docs_dir: docs
theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.sections
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Analysis and Configuration Guide: guide.md
  - Examples: examples.md
  - Tasks: tasks.md
  - Configs: configs.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table  # <--- Fondamentale per la griglia
            show_root_heading: true
            show_source: false
            # Nascondiamo i membri individuali così non vedi i doppioni in grassetto
            members: false 
            show_if_no_docstring: false
            show_default_values: true
            parse_refs: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: ["."]

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js