acquisition:
  date: "2026-01-19"
  chip: "W1a"
  structure: "43.3 um"
  drift: "fixed"
  back: "fixed"


# Properties of detector and source
detector:
  gas: argon
  w: 26.        # W-value of the gas in use (default is Ar)

source:
  element: 55Fe
  e_peak: 5.9   # Energy of the main emission line (K-alpha for 55Fe)


# Properties of the analysis pipeline
pipeline:
  - task: "calibration"
    charge_conversion: true
    plot: false
  
  - task: "spectrum_fitting"
    subtasks:
      - subtask: "main_peak"
        model: Fe55Forest
        fit_pars:
          xmin: -.inf
          xmax: .inf
          num_sigma_left: 1.5
          num_sigma_right: 1.5
          absolute_sigma: true

      # - subtask: "escape_peak"
      #   model: Gaussian
      #   fit_pars:
      #     xmin: 1.
      #     xmax: 3.

  - task: "gain"
    target: "main_peak"
    fit: true
    plot: true
    label: "test"
  
  - task: "resolution"
    target: "main_peak"
  
  # - task: "resolution_escape"
  #   target_main: "main_peak"
  #   target_escape: "escape_peak"

  - task: "plot"
    targets:
      - "main_peak"
      - "escape_peak"
    xrange: [2, 4]
    label: "chip"
    task_labels:
      - "gain"
      - "resolution"
      - "resolution_escape"

  - task: "plot"
    targets:
      - "escape_peak"
    label: "chip"
    task_labels:
      - "gain"
      - "resolution"
      - "resolution_escape"

  - task: "rate"
    target: "main_peak"
    threshold: 1.5

  - task: "plot"
    label: "test label"
