acquisition:
  date: "2026-01-01"
  chip: chip
  structure: structure
  gas: Ar
  w: 26.
  element: 55Fe
  e_peak: 5.9


pipeline:
  - task: calibration
    plot: false

  - task: fit_spec
    subtasks:
      - target: main
        model: Fe55Forest
  
  - task: gain
    target: main
    fit: true
    plot: true
    label: Gain exponential fit

  - task: resolution
    target: main
    label: Insert resolution label

  - task: plot
    targets:
      - main_peak
    label: Testing plot task
    task_labels:
      - gain
      - resolution