acquisition:
  date: "2026-01-1"
  chip: chip
  structure: structure
  gas: Ar
  w: 26.
  element: 55Fe
  e_peak: 5.9


pipeline:
  # Calibrate the ADC counts with the calibration file
  - task: calibration
    show: false

  - task: fit_spec
    subtasks:
    - target: main
      model: Fe55Forest
      fit_pars:
        xmin: 0.1

  - task: plot
    targets:
      - main
      - escape



