acquisition:
  date: "2026-01-19"
  chip: "W1a"
  structure: "43.3 um"
  drift: "fixed"
  back: "fixed"


# Properties of detector and source
detector:
  gas: argon
  w: 26.        # W-value of the gas in use (default is Ar)

source:
  element: 55Fe
  e_peak: 5.9   # Energy of the main emission line (K-alpha for 55Fe)


# Properties of the analysis pipeline
pipeline:
  - task: "calibration"
    charge_conversion: true
    plot: false

  - task: "spectrum_fitting"
    subtasks:
      - subtask: "main_peak"
        model: Gaussian
  

  
  - task: "gain_trend"
    time_unit: "h"    # Choices: s, m, h
    subtasks:
      - subtask: "charging"
        model: Constant + StretchedExponential
        init: [40., 25., 0.7, 0.6]
        xmin:
        xmax:
        absolute_sigma: true

      - subtask: "discharging"
        skip: true
        model: Constant + StretchedExponentialComplement
        init: []
        xmin:
        xmax:
        absolute_sigma: true
